### ISSUE TITLE
Global name 'theme' is not defined

### ISSUE THREAD

**Issue by quozl** [sugarlabs/cartoon-builder#2]
@zeecoder606, this error occurs when the reset button is clicked;

```
Traceback (most recent call last):
  File "/home/guest/Activities/CartoonBuilder.activity/activity.py", line 139, in __clear_tape_cb
    for i in range(theme.TAPE_COUNT):
NameError: global name 'theme' is not defined
```

And the reset does not happen.

**Comment by chimosky** [comment]
It happened because of the call to 'theme.TAPE_COUNT' which doesn't exist because of the import on line 36 so it's been changed to 'TAPE_COUNT'. Fix @[https://github.com/sugarlabs/cartoon-builder/pull/5](url), works fine now.
